set -e
case $1 in (prereqs) exit 0;; esac
. /usr/share/initramfs-tools/hook-functions
copy_exec /usr/bin/httpdirfs

# FIXME: get httpfs=https://⋯ working.
# Booting with "httpfs=https://example.com/" requires CA certs.
copy_file fuck /etc/ssl/certs/ca-certificates.crt
copy_file fuck /etc/ssl/certs/ssl-cert-snakeoil.pem
copy_file fuck /etc/ssl/openssl.cnf  # otherwise snakeoil cert isn't trusted????
# Because curl uses openssl and openssl looks for /etc/ssl/certs/<hash of cert> not /etc/ssl/certs/*,
# we have to include the symlink that is generated by c_rehash.
for i in /etc/ssl/certs/*.0
do
    if [ "$(readlink "$i")" = ssl-cert-snakeoil.pem ]
    then
        copy_file fuck "$i"
        break
    fi
done

# During testing I'll add a local dummy hostname.
copy_file fuck /etc/hosts
