include = [
    # For doing an initial install of Debian 12 onto ZFS (not actually understudy).
    'mmdebstrap', 'auto-apt-proxy',

    # EXT4 -> EXT4
    # -----------
    # FIXME: remove this block once all understudies are ZFS-based.
    'mdadm', 'lvm2', 'rsync',
    'e2fsprogs',        # no slow fsck on failover (e2scrub_all.timer)
    'quota',            # no slow quotacheck on failover

    # EXT4 -> ZFS
    # -----------
    # While the PrisonPC main server is ext4 and the understudy is ZFS,
    # we need cyber-zfs-backup on the UNDERSTUDY, so
    # that the main server can do "rsync to understudy, then on understudy make understudy-local ZFS snapshots".
    #
    # FIXME: Once the PrisonPC main server is also ZFS, remove cyber-zfs-backup from understudy.
    # In that case the main server just does "cyber-zfs-backup" which is main-server-local ZFS snapshots and a replication send-receive.
    'cyber-zfs-backup',

    # ZFS -> ZFS
    # ----------
    # NOTE: zfs-dkms will build zfs.ko for each installed linux-headers-X.
    #       If none are installed, zfs-dkms will no-op *WITHOUT ERROR*.
    #       Correct kernel header is in the debian-12-main.py script.
    'zfs-dkms',
    'zfs-zed',
    'zfsutils-linux',
]
