include = [
    "libnss-ldapd", "libpam-ldapd", "unscd",
    "nftables",
    # FIXME: move most of this shit into .tarinfo files.
    "nfs-client-quota",          # for quota-reminder.py
    "python3-gi", "gir1.2-gtk-3.0",  # for acceptable-use-policy.py
    "gir1.2-wnck-3.0",            # for popcon.py
    "gir1.2-notify-0.7",          # for log-terminal-attempt.py (et al)
    "libgtk-3-bin",  # gtk-launch (used by some .desktop files)
    "python3-systemd", "python3-pyudev",  # for *-snitch.py
    "python3-xdg",                     # for popcon.py
    "libgs9",                          # for lawyers-make-bad-pdfs/compress.py
    "genisoimage", "lsdvd",  # for disc-snitch.py
    "fonts-prisonpc",
    "x11vnc",  # https://en.wikipedia.org/wiki/Panopticon#Surveillance_technology
    "prayer-templates-prisonpc",
    "prisonpc-chromium-hunspell-dictionaries",
]
