include = [
    # workarounds for garbage hardware
    'firmware-bnx2',           # HCC's tvserver has evil Broadcom NICs
    # Used to build the shitty TBS driver & download the firmware blob.
    # See customize50-build-tbs-driver.py
    'build-essential', 'git', 'patchutils', 'libproc-processtable-perl',
    'wget2', 'bzip2',
    # Used at new sites to find frequency MHz.
    "w-scan",
]
