include = [
    "xserver-xorg-core", "xserver-xorg-input-libinput",
    "xfce4-session", "xfwm4", "xfdesktop4", "xfce4-panel", "thunar", "galculator",
    "xdm",
    # FIXME: in Debian 12, change --include=pulseaudio to --include=pipewire,pipewire-pulse
    # https://wiki.debian.org/PipeWire#Using_as_a_substitute_for_PulseAudio.2FJACK.2FALSA
    "pulseaudio", "xfce4-pulseaudio-plugin", "pavucontrol",
    # Without "alsactl init" & /usr/share/alsa/init/default,
    # pipewire/pulseaudio use the kernel default (muted & 0%)!
    # alsa-ucm-conf provides default mixer levels for AMCs "black chassis" SoC boards
    "alsa-utils", "alsa-ucm-conf",
    "ir-keytable",              # infrared TV remote control
    "xfce4-xkb-plugin",  # basic foreign language input (e.g. Russian, but not Japanese)
    "xdg-user-dirs-gtk",  # Thunar sidebar gets Documents, Music &c
    "gvfs", "thunar-volman", "eject",  # Thunar trash://, DVD autoplay, DVD eject
    "xfce4-notifyd",            # xfce4-panel notification popups
    # FIXME: use plocate (not mlocate) once PrisonPC master server upgrades!
    "catfish", "mlocate", "xfce4-places-plugin",  # "Find Files" tool
    "eog",            # chromium cant flip between 1000 photos quickly
    "usermode",                         # password reset tool
    "librsvg2-common",                  # SVG icons in GTK3 apps
    "gnome-themes-extra", "adwaita-qt",  # theming
    "at-spi2-core", "gnome-accessibility-themes",
    "plymouth-themes",
]
