include = [
    "xserver-xorg-core", "xserver-xorg-input-libinput",
    "xfce4-session", "xfwm4", "xfdesktop4", "xfce4-panel", "thunar", "galculator",
    "xdm",
    # https://wiki.debian.org/PipeWire#Debian_12
    # FIXME: do we need/want vlc-plugin-pipewire?
    "pipewire-audio", "xfce4-pulseaudio-plugin", "pavucontrol",
    # Without "alsactl init" & /usr/share/alsa/init/default,
    # pipewire/pulseaudio use the kernel default (muted & 0%)!
    # UPDATE: in Debian 12, pipewire defaults to 40% with or without alsa-utils/alsa-ucm-conf.
    # alsa-ucm-conf provides default mixer levels for AMCs "black chassis" SoC boards
    # "alsa-utils", "alsa-ucm-conf",
    "xfce4-xkb-plugin",  # basic foreign language input (e.g. Russian, but not Japanese)
    "xdg-user-dirs-gtk",  # Thunar sidebar gets Documents, Music &c
    "gvfs", "thunar-volman", "eject",  # Thunar trash://, DVD autoplay, DVD eject
    "xfce4-notifyd",            # xfce4-panel notification popups
    # FIXME: use plocate (not mlocate) once PrisonPC master server upgrades!
    "catfish", "plocate", "xfce4-places-plugin",  # "Find Files" tool
    "eog",            # chromium cant flip between 1000 photos quickly
    "usermode",                         # password reset tool
    "librsvg2-common",                  # SVG icons in GTK3 apps
    "gnome-themes-extra", "adwaita-qt",  # theming
    "at-spi2-core", "gnome-accessibility-themes",
    "plymouth-themes",

    # Accelerated graphics drivers for several libraries & GPU families
    "vdpau-driver-all",  # VA/AMD, free
    "mesa-vulkan-drivers",     # Intel/AMD/Nvidia, free
    "va-driver-all",           # Intel/AMD/Nvidia, free
    "i965-va-driver-shaders",  # Intel, non-free, 2013-2017
    "intel-media-va-driver-non-free",  # Intel, non-free, 2017+

    # Seen on H81 and H110 Pioneer AIOs.
    # Not NEEDED, just makes journalctl -p4' quieter.
    "firmware-realtek", "firmware-misc-nonfree",
]
