Explanation: many pattern with many matches, spread over many rules, with the different priorities
Pin-Priority: -1
Pin: version *
Package: *-dev

Pin-Priority: -2
Pin: version *
Package: *-devel

Pin-Priority: -5
Pin: version *
Package: *-dbg

Pin-Priority: -10
Pin: version *
Package: *-dbgsym

Pin-Priority: -20
Pin: version *
Package: *-prof

Pin-Priority: -50
Pin: version *
Package: *-src

Pin-Priority: -100
Pin: version *
Package: *-source

Pin-Priority: -200
Pin: version *
Package: *-dkms

Pin-Priority: -500
Pin: version *
Package: *-debug

Pin-Priority: -1000
Pin: version *
Package: *-compiler

Pin-Priority: -2000
Pin: version *
Package: *-test

Pin-Priority: -5000
Pin: version *
Package: *-tests

Pin-Priority: -10000
Pin: version *
Package: libghc-*-doc
