Explanation: test 60 literals (not globs/regexps) -- are literals OK?
Pin-Priority: -1
Pin: version *
Package:
 src:libreoffice
 src:linux
 clang-17-doc clang-17-examples clang-17 clang-18-doc
 clang-18-examples clang-18 clang-19-doc clang-19-examples clang-19
 clang-21-doc clang-21-examples clang-21 clang-format-17
 clang-format-18 clang-format-19 clang-format-21 clang-format
 clang-tidy-17 clang-tidy-18 clang-tidy-19 clang-tidy-21 clang-tidy
 clang-tools-17 clang-tools-18 clang-tools-19 clang-tools-21
 clang-tools
 llvm-17-dev llvm-17-doc llvm-17-examples llvm-17-linker-tools
 llvm-17-runtime llvm-17-tools llvm-17 llvm-18-dev llvm-18-doc
 llvm-18-examples llvm-18-linker-tools llvm-18-runtime llvm-18-tools
 llvm-18 llvm-19-dev llvm-19-doc llvm-19-examples llvm-19-linker-tools
 llvm-19-runtime llvm-19-tools llvm-19 llvm-21-dev llvm-21-doc
 llvm-21-examples llvm-21-linker-tools llvm-21-runtime llvm-21-tools
 llvm-21 llvm-bolt llvm-dev llvm-libunwind1 llvm-runtime llvm-spirv-17
 llvm-spirv-18 llvm-spirv-19
