Explanation: many pattern with many matches, spread over many rules, with very negative priorities
Pin-Priority: -32000
Pin: version *
Package: *-dev

Pin-Priority: -31000
Pin: version *
Package: *-devel

Pin-Priority: -30000
Pin: version *
Package: *-dbg

Pin-Priority: -29000
Pin: version *
Package: *-dbgsym

Pin-Priority: -28000
Pin: version *
Package: *-prof

Pin-Priority: -27000
Pin: version *
Package: *-src

Pin-Priority: -26000
Pin: version *
Package: *-source

Pin-Priority: -25000
Pin: version *
Package: *-dkms

Pin-Priority: -24000
Pin: version *
Package: *-debug

Pin-Priority: -23000
Pin: version *
Package: *-compiler

Pin-Priority: -22000
Pin: version *
Package: *-test

Pin-Priority: -21000
Pin: version *
Package: *-tests

Pin-Priority: -20000
Pin: version *
Package: libghc-*-doc
