Explanation: OK, does merging those fnmatch patterns into a regex pattern run faster?
    ELISP> (rx bol
               (or (and (or "dh-" "lib32" "libx32" "r-") (zero-or-more any))
                   (and "libghc-" (zero-or-more any) "-doc")
                   (and (zero-or-more any) (or "askpass" "emacs" "firmware" "vim" "tree-sitter") (zero-or-more any))
                   (and (zero-or-more any) (or "-dev" "-devel" "-server" "-dbg" "-dbgsym" "-prof" "-src" "-source" "-dkms" "-debug" "-compiler" "-test" "-tests"))
                   "zip")
               eol)
    ELISP> (rx bol 
               (or (and (or "gcr" "gnupg" "libarchive") (zero-or-more any))
                   (and "libghc-" (zero-or-more any) "-doc")
                   (and (zero-or-more any) (or "7zip" "askpass" "avahi" "bluetooth" "bluez" "dnssd" "emacs" "firmware" "iupdown" "kwallet" "libnma" "mdns" "modem" "netplan" "nettle" "network-manager" "p11" "resolvconf" "secret" "sequoia" "sourceview" "wifi" "wi-i" "wireless") (zero-or-more any))
                   "gnome-keyring"
                   "gnome-keysign"
                   "pinentry"
                   "qca2"
                   "seahorse"
                   "zip")
               eol)
Pin-Priority: -1
Pin: version *
Package:
 /^((dh-|lib(x?32)|r-).*|libghc-.*-doc|.*(askpass|emacs|firmware|tree-sitter|vim).*|.*(-(compiler|d(bg(sym)?|e(bug|v(el)?)|kms)|prof|s(erver|ource|rc)|tests?))|zip)$/
 src:/^((g(cr|nupg)|libarchive).*|libghc-.*-doc|.*(7zip|a(skpass|vahi)|blue(tooth|z)|dnssd|emacs|firmware|iupdown|kwallet|libnma|m(dns|odem)|net(plan|tle|work-manager)|p11|resolvconf|s(e(cret|quoia)|ourceview)|wi(-i|fi|reless)).*|gnome-keyring|gnome-keysign|pinentry|qca2|seahorse|zip)$/
