Explanation: many source patterns with few matches
Pin-Priority: -1
Pin: version *
Package:
 src:lib*troutoverpassnaturehandrailslicedunwrapped*
 src:lib*silicacollectedrewinddespiteskincarequarterly*
 src:lib*headfirststimuluscascadeunchainastoundclapping*
 src:lib*snooperreversalbonnetoutrightpaternalsqueezing*
 src:lib*skeletalvivaciouscommenceaffordsubleasemuppet*
 src:lib*attendeeacrobatabacusunnervealtitudeheadphone*
 src:lib*exclusiontarmacbasketmanagingoversightsplashed*
 src:lib*rentableaerosoldaylonggranolaemblazehuddling*
 src:lib*dastardlygropemangoepidermisimplicateconcierge*
 src:lib*gravesundercoatantitoxicobservantenlargedstiffly*
 src:lib*hastilyhatlessstashprocurerurgingchastity*
 src:lib*shindigchlorideoverpricegrandpacollidepapyrus*
 src:lib*carvingcattyunlovingprunereformedunsolved*
