Explanation: many pattern with few matches
Pin-Priority: -1
Pin: version *
Package:
 lib*troutoverpassnaturehandrailslicedunwrapped*
 lib*silicacollectedrewinddespiteskincarequarterly*
 lib*headfirststimuluscascadeunchainastoundclapping*
 lib*snooperreversalbonnetoutrightpaternalsqueezing*
 lib*skeletalvivaciouscommenceaffordsubleasemuppet*
 lib*attendeeacrobatabacusunnervealtitudeheadphone*
 lib*exclusiontarmacbasketmanagingoversightsplashed*
 lib*rentableaerosoldaylonggranolaemblazehuddling*
 lib*dastardlygropemangoepidermisimplicateconcierge*
 lib*gravesundercoatantitoxicobservantenlargedstiffly*
 lib*hastilyhatlessstashprocurerurgingchastity*
 lib*shindigchlorideoverpricegrandpacollidepapyrus*
 lib*carvingcattyunlovingprunereformedunsolved*
