Explanation: trying to get it all the way up to 10 seconds elapsed like I saw in the field
Pin-Priority: -1
Pin: version *
Package:
 *-dev devel server libghc-*-doc dbg dbgsym prof src source dkms debug
 *-compiler test tests *firmware* src:*firmware* libx32* lib32*
 *tree-sitter* src:*tree-sitter* *vim* src:*vim* *emacs* src:*emacs*
 dh-*
 zip src:zip src:*7zip* src:rar* src:*unrar* src:libarchive*
 src:*secret* src:qca2
 r-*
 src:*sourceview* src:gnupg* src:*sequoia* src:*nettle* *askpass*
 src:*askpass* src:pinentry src:*p11*
 src:*kwallet* src:gcr* src:seahorse src:gnome-keyring
 src:gnome-keysign
 src:*bluez* src:*bluetooth* src:*avahi* src:*mdns* src:*dnssd*
 src:*network-manager* src:*libnma* src:*ifupdown* src:*netplan*
 src:*resolvconf*
 src:*modem* src:*wireless* src:*wifi* src:*wi-fi*
