Explanation: many pattern with many matches, spread over many rules, with the same priority
Pin-Priority: -1
Pin: version *
Package: *-dev

Pin-Priority: -1
Pin: version *
Package: *-devel

Pin-Priority: -1
Pin: version *
Package: *-dbg

Pin-Priority: -1
Pin: version *
Package: *-dbgsym

Pin-Priority: -1
Pin: version *
Package: *-prof

Pin-Priority: -1
Pin: version *
Package: *-src

Pin-Priority: -1
Pin: version *
Package: *-source

Pin-Priority: -1
Pin: version *
Package: *-dkms

Pin-Priority: -1
Pin: version *
Package: *-debug

Pin-Priority: -1
Pin: version *
Package: *-compiler

Pin-Priority: -1
Pin: version *
Package: *-test

Pin-Priority: -1
Pin: version *
Package: *-tests

Pin-Priority: -1
Pin: version *
Package: libghc-*-doc
