Explanation: one pattern but a very negative priority
 The idea being that if you have a complicated set of negative pins,
 you can tell which pattern matched by looking at the number it was pinned to.
Pin-Priority: -32000
Pin: version *
Package: marble
