# In Debian 9 this used a different file format.
# The change happened around 2018:
#     https://github.com/gjasny/v4l-utils/commit/3646338
#     https://github.com/gjasny/v4l-utils/commit/0547426

[[protocols]]
name = "PrisonPC"
protocol = "nec"
variant = "nec"

# Layout of our PrisonPC remotes (v2 safety pack)
# ╔════╤════╤════╗     ╔════╤════╤════╗
# ║ 5c │    │ 1e ║     ║POWR│    │MENU║
# ╟────┼────┼────╢     ╟────┼────┼────╢
# ║ 58 │ 1b │ 16 ║     ║STAR│ UP │STTL║
# ╟────┼────┼────╢     ╟────┼────┼────╢
# ║ 55 │ 17 │ 15 ║     ║LEFT│ENTR│RGHT║
# ╟────┼────┼────╢     ╟────┼────┼────╢
# ║ 59 │ 10 │ 18 ║     ║ESC │DOWN│INFO║
# ╟────┼────┼────╢     ╟────┼────┼────╢
# ║ 5d │ 1f │ 1c ║     ║MUTE│SOFT│LOUD║
# ╟────┴────┴────╢     ╟────┴────┴────╢
# ║              ║     ║              ║
# ║  PrisonPC >  ║     ║  PrisonPC >  ║
# ╚══════════════╝     ╚══════════════╝

# The first field is what the remote sends.
# The second field is an input.h keysym.
[protocols.scancodes]
0x5c  = "KEY_CLOSE"
0x1e  = "KEY_MENU"
0x58  = "KEY_CONNECT"
0x1b  = "KEY_UP"
0x16  = "KEY_CHAT"
0x55  = "KEY_LEFT"
0x17  = "KEY_ENTER"
0x15  = "KEY_RIGHT"
0x59  = "KEY_ESC"
0x1a  = "KEY_DOWN"
0x18  = "KEY_HELP"
0x5d  = "KEY_MUTE"
0x1d  = "KEY_VOLUMEDOWN"
0x1c  = "KEY_VOLUMEUP"

# Here is how you turn e.g. KEY_POWER (Linux) into XF86PowerOff (Xorg).
# The input.h number is *EIGHT LESS* than evdev number!
#
#     /usr/include/linux/input.h        (linux:include/.../input.h)
#     /usr/share/X11/xkb/keycodes/evdev (xkeyboard-config:symbols/inet)
#     /usr/share/X11/xkb/symbols/inet   (xkeyboard-config:keycodes/evdev)
#
#     --> #define KEY_POWER 116
#     --> <POWR> = 124;
#     --> key <POWR> { [ XF86PowerOff ] };
#
# Here are some I prepared earlier:
#
#     kName           kCode  xCode  xKey  xSym
#     =====           =====  =====  ====  ====
#     KEY_UP          103    111    UP    XF86MenuPB
#     KEY_DOWN        108    116    DOWN  XF86ScrollDown
#     KEY_LEFT        105    113    LEFT
#     KEY_RIGHT       106    114    RGHT
#     KEY_ENTER       28     36     RTRN  Return
#     KEY_ESC         1      9      ESC
#
#     KEY_VOLUMEDOWN  114    122    VOL-  XF86AudioLowerVolume
#     KEY_VOLUMEUP    115    123    VOL+  XF86AudioRaiseVolume
#     KEY_MUTE        113    121    MUTE  XF86AudioMute
#
#     KEY_CLOSE       206    214    I214  XF86Close
#     KEY_MENU        139    147    I147  XF86MenuKB
#     KEY_CONNECT     218    226    I226  XF86Go
#     KEY_CHAT        216    224    I224  XF86Messenger
#     KEY_HELP        138    146    HELP  Help
#
# Due to limits in the X11 protocol,
# Xorg CANNOT SEE Linux keycodes greater than 256.
# This includes KEY_INFO and KEY_SUBTITLE.
# Ref. https://bugs.freedesktop.org/show_bug.cgi?id=x11-keycode-limit
# Therefore I have unilaterally chosen these subtitutes:
#   KEY_SUBTITLE -> KEY_F23
#   KEY_INFO     -> KEY_F24
# --twb, Oct 2015
#
# Mike historically configured the red power button run "pkill upmc".
# Therefore I am renaming it from KEY_POWER to KEY_CLOSE,
# and I will make it act like Alt+F4 (close focused window).
# --twb, Oct 2015
#
# Mike historically left the STAR key undefined.
# For now, I have made that KEY_MENU (open Apps menu),
# and the MENU key KEY_CONTEXT_MENU (right-click menu).
# --twb, Oct 2015
