#!/bin/sh
set -e

# NOTE: for now, we only support install, not remove/purge.
if [ "$1" = triggered ] || [ "$1" = configure ]
then
    # As at Debian 11, KDE manuals are installed in one place:
    # /usr/share/doc/kde/HTML/en  (gone, KDE4 only)
    # /usr/share/doc/HTML/en

    [ ! -d /usr/share/doc/HTML/ ] ||
    find /usr/share/doc/HTML/ -name index.docbook |
    while read -r path
    do
        lang=${path#/*/*/*/*/} lang=${lang%%/*} newlang=$lang
        [ "$newlang" != en ] || newlang=C  # KDE en becomes GNOME C
        name=${path#/*/*/*/*/*/} name=${name%/index.docbook}
        newpath=/usr/share/help/"$newlang"/"$name"

        [ ! -e "$newpath" ] || continue

        echo >&2 "Converting $path..."
        mkdir -p "${newpath%/*}"
        ln -sT "${path%/*}" "$newpath"
        ln -st "$newpath" /usr/share/kf5/kdoctools/customization/dtd
        ln -st "$newpath" /usr/share/kf5/kdoctools/customization/entities
        ln -st "$newpath" /usr/share/kf5/kdoctools/customization/"$lang"

        # FIXME: is this line obsolete as at Debian 10?
        # NOTE: using regexp replacement on XML is morally wrong!
        # NOTE: no ^ because marble & kalzium have leading whitespace.
	# FIXME: use python or xslt or something instead?
        sed -i 's/<book id="[^"]*"/<book id="index"/' "$newpath/index.docbook"
    done

    # FIXME: I'm 60% sure pre-rendered HTML was a KDE4 thing, and this block is obsolete/useless.
    # The pre-rendered versions are no longer needed.
    [ ! -d /usr/share/doc/HTML/ ] ||
    find /usr/share/doc/HTML/ '(' -name index.cache.bz2 -o -name '*.html' -o -name '*.css' ')' -delete
fi

#DEBHELPER#
