#!/bin/sh
[ prereqs = "$1" ] && exit      # do nothing at ramdisk build time

# GOAL: try to configure rsyslog and msmtp BEFORE systemd starts,
#       so that central logging can happen a little earlier.
#       Really, I'm just worried about getting "host X started" logs forwarded by rsyslog.
#       FIXME: This might be a premature optimization!!!

# apt-helper has to be chrooted to run, but
# when chrooted, /etc/resolv.conf points to resolved, which is not up yet.
# Hacky workaround: swap resolve.conf, do the lookup, swap it back.

mv /root/etc/resolv.conf /root/etc/resolv.conf.real
cp /etc/resolv.conf /root/etc/resolv.conf
if chroot /root /sbin/bootstrap2020-get-config-from-dnssd
then
    # Don't bother to run the post-pivot_root version.
    chroot /root systemctl --root=/ disable bootstrap2020-get-config-from-dnssd
fi
mv /root/etc/resolv.conf.real /root/etc/resolv.conf
