#!/usr/bin/python3
import pathlib
import re
import subprocess
import logging

__doc__ = """ work around warzone2100 bug

We can place warzone2100 addons in
/usr/share/games/warzone2100/maps/X.wz and
/usr/share/games/warzone2100/mods/Y.wz.

Warzone2100 FINDS these files, but it READS from
~/.local/share/warzone2100-$VERSION/maps/X.wz and
~/.local/share/warzone2100-$VERSION/mods/Y.wz.
This is a bug in warzone2100.

As a workaround, symlink the latter to the former.

NOTE: this breaks map auto-download for online play.
PrisonPC does not allow online play, so we don't care.
—twb, Sep 2017
https://alloc.cyber.com.au/task/task.php?taskID=31556

UPDATE 2022: in Debian 11 / warzone2100 3.3, symlinking the whole directory no longer works.
I think the warzone2100 code is doing stat() instead of lstat(), so treating a symlink as "not a directory".
Let's try symlinking individual files.

UPDATE: all this bullshit IS still needed in Debian 12.
        The paths have changed slightly:

        WAS ~p123/.local/share/warzone2100-$VERSION/mods/global/ARmod_$VERSION.wz
        NOW ~p123/.local/share/warzone2100/mods/$VERSION/global/ARmod_$VERSION.wz

"""

# FIXME: in Python3.5+ use subprocess.run instead of the try/except shit!
proc = subprocess.run(
    ['/usr/games/warzone2100', '--version'],
    stdout=subprocess.PIPE,
    text=True,
    check=False)
if proc.returncode != 1:
    raise RuntimeError('warzone2100 --version should always exit(1)!')

# Example: Warzone 2100 - Version: 3.3.0, Built: 2020-10-16
version = re.fullmatch(
    r'Warzone 2100 - Version: (\d+\.\d+\.\d+), .*',
    proc.stdout.strip()).group(1)

# 13:50:05: [listMapFiles:678]
#           Could not mount /home/prisoners/p123/.local/share/warzone2100//maps/10c-DA-BDCTW10-v1max.wz, because:
#           not found.  Please delete or move the file specified.
# access("/home/prisoners/p123/.local/share/warzone2100//mods/4.3.3/global/ARmod_4.0.1.wz", W_OK) = -1 EACCES (Permission denied)
# newfstatat(AT_FDCWD, "/home/prisoners/p123/.local/share/warzone2100//mods/4.3.3/global/ARmod_4.0.1.wz", {st_mode=S_IFLNK|0777, st_size=55, ...}, AT_SYMLINK_NOFOLLOW) = 0
for srcs, dst in {
        # Skirmish maps are in an unversioned dir.
        (pathlib.Path('/usr/share/games/warzone2100/maps').glob('*.wz'),
         pathlib.Path.home() / '.local/share/warzone2100/maps'),
        # The one mod (for high-res textures) is in a versioned dir.
        (pathlib.Path('/usr/share/games/warzone2100/mods/global').glob('*.wz'),
         pathlib.Path.home() / f'.local/share/warzone2100/mods/{version}/global')}:
    dst.mkdir(exist_ok=True, parents=True)
    for src in srcs:
        try:
            (dst / src.name).symlink_to(src)
        except FileExistsError:
            logging.debug('already exists -- assuming already correct', src)
