include = [
    "libnss-ldapd", "libpam-ldapd", "unscd",
    "nftables",
    "fonts-prisonpc",
    "prisonpc-chromium-hunspell-dictionaries",
]


###
### Workaround https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1133971#10
###
both_shit_regexps = [
    ## Inmates MUST NOT have unnecessary crypto
    ## ========================================
    "gnupg",
    "sequoia",
    "crypt",
    "^libreoffice.*-nogui$",    # encrypted zip?

    ## Inmates MUST NOT have clandestine comms
    ## =======================================
    "^ircd",
    "^asterisk",
    "^efax",

    ## Inmates MUST NOT have writable local media (DVD, USB)
    ## =====================================================
    ## Inmates MUST NOT have containers (VMs)
    ## ======================================
    ## Inmates MUST NOT have root REPL (& SHOULD NOT get any REPL)
    ## ===========================================================
    ## Inmates SHOULD NOT have a text editor
    ## =====================================
    "vim",
    "emacs",
    "^elpa-",
    "-el$",

    ## Inmates SHOULD NOT have access to cron-style scheduling (#30091)
    ## ================================================================
    ## Inmates SHOULD NOT have miscellaneous scary things
    ## ==================================================
    ## Inmates SHOULD NOT be able to use VLC for evil
    ## ==============================================
    ## Inmates SHOULD NOT have packaging tools
    ## =======================================
    "package.*kit",
    "^python.*apt",
    "^dpkg-dev$",

    ## Inmates SHOULD NOT have diagnostic tools
    ## ========================================
    "^iproute2$",
    "^acl$",
    "^gdb$",
    "^gdb-",
    "^kf6-kxmlgui$",

    ## Inmates SHOULD NOT have development tools
    ## =========================================
    "-dev$",
    "-devel$",
    "-dbg$",
    "-test$",
    "-tests$",
    "^libghc-.+-doc$",
    "^ros2-",
    "^binutils-",
    "cuda",                     # fuck Nvidia
    "nvidia",                   # fuck Nvidia
    "android",                  # fuck Google
    "^gcc-defaults",
    "^gcc-.+-cross",
    "^linux-source",
    "^linux-source-",
    "^linux-config-",
    "^linux-headers-",
    "^linux-kbuild-",
    "^linux-board-support-package-",
    "^cross-toolchain-base$",
    "^dh-",
    "^rust-cargo-",
    "^llvm-[0-9][0-9]",
    "spriv",
    "autoconf",
    "golang-.+-go",
    "geany",
    "kdevelop",
    "jupyter",
    "idle-python",
    "yorick",
    "-venv$",
    # version control stuff
    "^git",
    "^mercurial",
    "^rcs",
    "^svn",
    "^subversion",
    "^fossil",
    "^breezy",
    "^bazaar",
    "^darcs",

    ## Useless & confusing menu items SHOULD be hidden (#30257)
    ## ========================================================
    ## Useless & confusing "under the hood" files MAY be removed
    ## =========================================================
    ## sysvinit compatibility MAY be removed
    ## =====================================
    ## Inmates SHOULD NOT be able to make screenshots
    ## ==============================================
    ## Everything else
    ## ===============
    "^lib32",
    "^libx32",
    "lomiri",                   # smartphone stuff
    "zope",                     # web
    "mariadb",
    "^nupkg",
]


deb_good_regexps = [
    "sqv",                      # apt → sqv
    "cpp",                      # xdm → cpp
    "cpp-x86-64-linux-gnu",     # xdm → cpp → arch-specific bullshit
    "python3-numpy-dev",  # singularity → python3-numpy → python3-numpy-dev
    "libcrypt1",      # init → systemd → libsystemd-shared → libcrypt1
    "libsecret-1-0",  # msmtp-mta → libsecret-1-0 → libgcrypt20
    "libgcrypt20",    # msmtp-mta → libsecret-1-0 → libgcrypt20
    "libblockdev-crypto3",      # udisks2 → libblockdev-crypto
    "libcryptsetup12",  # udisks2 → libblockdev-crypto → libcryptsetup
    "libngtcp2-crypto-.*[0-9]",  # libreoffice → libcurl → libngtcp2-crypto
    "libgssapi-krb5-2",          # libcups → src:krb5 stuff
    "libk5crypto3",              # libcups → src:krb5 stuff
    "libkrb5-3",                 # libcups → src:krb5 stuff
    "libkrb5support0",           # libcups → src:krb5 stuff
    "libmbedcrypto16",  # vlc → vlc-plugins-base → libavformat64 → librist4 → libmbedcrypto16
]
