#!/bin/sh

# GOAL: inform networkd & resolved about the boot interface;
#       get DHCPv6 lease; renew DHCPv4 lease.
#
# NOTE: when netbooting, during initrd (before pivot_root),
#       /lib/live/boot/9990-networking.sh runs
#       /usr/lib/klibc/bin/ipconfig
#       which gives us a DHCPv4 lease.
#       If we do nothing, we keep using this lease without renewing it!
#       The same code will create /etc/resolv.conf UNLESS it already exists.
#
# NOTE: pxelinux.0 adds BOOTIF= to /proc/cmdline when pxelinux.cfg contains IPAPPEND 2.
#
# NOTE: systemd-network-generator understands ifname= (not BOOTIF=) so we can't use it.

[ prereqs = "$1" ] && exit      # do nothing at ramdisk build time
[ -n "$BOOTIF" ] || exit  # do nothing unless BOOTIF= in /proc/cmdline

# NOTE: I tried putting this into /run/systemd/network, but systemd-networkd v247 just ignored it.
mkdir -p /root/etc/systemd/network/50-bootstrap2020.network.d
cat     >/root/etc/systemd/network/50-bootstrap2020.network.d/inherit-pxelinux-nic.conf <<-EOF
[Match]
MACAddress=${BOOTIF#01-}
EOF

cat     >/root/etc/systemd/network/50-bootstrap2020.network.d/my-rootfs-is-on-this.conf <<-EOF
# Tell systemd-network that we need this iface to access our root filesystem.
# Without this, systemd-networkd lowers the interface at shutdown time,
# then can't find the /sbin/shutdown program to do the final shutdown/reboot!
# NOTE: in systemd v243 DHCP.CriticalConnection became Network.KeepConnection
[Network]
KeepConfiguration=yes
EOF
