# FIXME: have ukify use sbsign to sign the linuxx64.efi.
#        Also sign filesystem.squashfs somehow?


[UKI]
Linux=/vmlinuz
Initrd=/initrd.img
# FIXME: As at 2023, /proc/cmdline must be specified at boot time (not ukify time).
#        At a minimum this is needed for understudy's personality=alice hack.
#        For secure boot, that MUST become a static /proc/cmdline, done here.
#        UPDATE: for secure boot, this SHOULD be set statically here.
#        But as PrisonPC does not currently support that, if
#        we *don't* set it here,
#        systemd-shim will accept dynamic (including attacker-supplied) cmdline.
#        Therefore, don't set it here.
# Cmdline=boot=live
